"""Add user key_api

Revision ID: 091ce3394680
Revises: 7cd8780ab650
Create Date: 2020-10-08 10:59:27.424858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091ce3394680'
down_revision = '7cd8780ab650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
